Models/Persona.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace proyectoABMC.Models
{
    public class Persona
    {
        [Key]
        public int PersonaId { get; set; }

        [Required(ErrorMessage = "Este campo es requerido")]
        [MaxLength(50, ErrorMessage = "La longitud máxima del campo es de 50 caracteres")]
        [Display(Name = "Nombre")]
        public string Nombre { get; set; }

        [Required(ErrorMessage = "Este campo es requerido")]
        [Display(Name = "Fecha de Nacimiento")]
        public DateTime FechaNacimiento { get; set; }

        [Required(ErrorMessage = "Este campo es requerido")]
        [Range(0, 999999999999999999.99)]
        [Display(Name = "Credito Maximo")]
        public int CreditoMaximo { get; set; }
    }
}

Controllers/PersonasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using proyectoABMC.Database;
using proyectoABMC.Models;

namespace proyectoABMC.Controllers
{
    public class PersonasController : Controller
    {
        private readonly ProyectoAbmcDbContext _context;

        public PersonasController(ProyectoAbmcDbContext context)
        {
            _context = context;
        }

        public IActionResult Index(string? nombre)
        {
            if (nombre != null)
            {
                return View(nameof(Index), _context.Personas.Where(P => P.Nombre.Equals(nombre)).ToList());
            }
            return View(_context.Personas.ToList());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("PersonaId,Nombre,FechaNacimiento,CreditoMaximo")] Persona persona)
        {
            if (ModelState.IsValid)
            {
                _context.Add(persona);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(persona);
        }

        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var persona = _context.Personas.Find(id);
            if (persona == null)
            {
                return NotFound();
            }
            return View(persona);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("PersonaId,Nombre,FechaNacimiento,CreditoMaximo")] Persona persona)
        {
            if (id != persona.PersonaId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(persona);
                    _context.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PersonaExists(persona.PersonaId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(persona);
        }


        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var persona = _context.Personas
                .FirstOrDefault(m => m.PersonaId == id);
            if (persona == null)
            {
                return NotFound();
            }

            return View(persona);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var persona = _context.Personas.Find(id);
            _context.Personas.Remove(persona);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        private bool PersonaExists(int id)
        {
            return _context.Personas.Any(e => e.PersonaId == id);
        }
    }
}

Controllers/TelefonosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using proyectoABMC.Database;
using proyectoABMC.Models;

namespace proyectoABMC.Controllers
{
    public class TelefonosController : Controller
    {
        private readonly ProyectoAbmcDbContext _context;

        public TelefonosController(ProyectoAbmcDbContext context)
        {
            _context = context;
        }

        public IActionResult Index(int id)
        {
            if (id != 0)
            {
                return View(nameof(Index),_context.Telefonos.Where(P => P.PersonaID.Equals(id)).ToList());
            }
            return View(_context.Telefonos.ToList());
        }

        public IActionResult Create(int id)
        {
            ViewData["PersonaId"] = new SelectList(_context.Personas.Where(P => P.PersonaId.Equals(id)), "PersonaId", "Nombre");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Telefono telefono)
        {
            if (ModelState.IsValid)
            {
                _context.Add(telefono);
                _context.SaveChanges();
                return Index(id:telefono.PersonaID);
            }
            ViewData["PersonaID"] = new SelectList(_context.Personas, "PersonaId", "Nombre", telefono.PersonaID);
            return View(telefono);
        }

        public IActionResult Edit(int? id)
        {
            ViewData["PersonaId"] = new SelectList(_context.Personas, "PersonaId", "Nombre");
            if (id == null)
            {
                return NotFound();
            }

            var telefono = _context.Telefonos.Find(id);
            if (telefono == null)
            {
                return NotFound();
            }
            return View(telefono);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, Telefono telefono)
        {
            if (id != telefono.TelefonoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(telefono);
                    _context.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TelefonoExists(telefono.TelefonoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["PersonaID"] = new SelectList(_context.Personas, "PersonaId", "Nombre", telefono.PersonaID);
            return View(telefono);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var telefono = _context.Telefonos
                .FirstOrDefault(m => m.TelefonoId == id);
            if (telefono == null)
            {
                return NotFound();
            }

            return View(telefono);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var telefono = _context.Telefonos.Find(id);
            _context.Telefonos.Remove(telefono);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        private bool TelefonoExists(int id)
        {
            return _context.Telefonos.Any(e => e.TelefonoId == id);
        }
    }
}

Views/Personas/Create.cshtml
@model proyectoABMC.Models.Persona

@{
    ViewData["Title"] = "Create";
}

<h1>Añadir Persona.</h1>

<h4>Persona</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaNacimiento" class="control-label"></label>
                <input asp-for="FechaNacimiento" class="form-control" type="date"/>
                <span asp-validation-for="FechaNacimiento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreditoMaximo" class="control-label"></label>
                <input asp-for="CreditoMaximo" class="form-control" />
                <span asp-validation-for="CreditoMaximo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-danger">Cancelar</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Personas/Delete.cshtml
@model proyectoABMC.Models.Persona

@{
    ViewData["Title"] = "Delete";
}

<h3>Confirmacion de eliminacion de la persona @Model.Nombre </h3>
<div>
    <h4>Persona</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaNacimiento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaNacimiento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreditoMaximo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreditoMaximo)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="PersonaId" />
        <input type="submit" value="Borrar" class="btn btn-danger" />
        <a asp-action="Index" class="btn btn-success">Cancelar</a>
    </form>
</div>

Views/Personas/Edit.cshtml
@model proyectoABMC.Models.Persona

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar datos de @Model.Nombre</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PersonaId" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaNacimiento" class="control-label"></label>
                <input asp-for="FechaNacimiento" class="form-control" />
                <span asp-validation-for="FechaNacimiento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreditoMaximo" class="control-label"></label>
                <input asp-for="CreditoMaximo" class="form-control" />
                <span asp-validation-for="CreditoMaximo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-danger">Cancelar</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Personas/Index.cshtml
@model IEnumerable<proyectoABMC.Models.Persona>

@{
    ViewData["Title"] = "Index";
}

<h1 class="d-flex justify-content-center">Grilla de personas</h1>

<div class="d-flex justify-content-between mb-3">
    <a asp-action="Create" class="btn btn-primary">Añadir persona</a>

    <form asp-action="Index" class="d-flex justify-content-end">
        <div class="input-group">
            <input type="text" placeholder="Search.." name="nombre" class="form-control">
            <div class="input-group-prepend">
                <input type="submit" value="Buscar" class="btn btn-outline-secondary">
            </div>
        </div>
    </form>

</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaNacimiento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreditoMaximo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Convert.ToString(string.Format("{0:dd/MM/yyyy}", item.FechaNacimiento))
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreditoMaximo)
                </td>
                <td class="d-flex justify-content-end">
                    <a asp-action="Edit" asp-route-id="@item.PersonaId" class="btn btn-outline-info">Editar</a>
                    <a asp-action="Delete" asp-route-id="@item.PersonaId" class="btn btn-outline-danger">Borrar</a>
                    <a asp-controller="Telefonos" asp-action="Index" asp-route-id="@item.PersonaId" class="btn btn-outline-primary">Ver Telefonos</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<hr />
<p class="d-flex justify-content-end">
    <a asp-action="Create" class="btn btn-primary">Añadir persona</a>
</p>