Models/Telefono.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace proyectoABMC.Models
{
    public class Telefono
    {
        [Key]
        public int TelefonoId { get; set; }

        [Required(ErrorMessage = "Este campo es requerido")]
        [ForeignKey(nameof(Persona))]
        [Display(Name = "Id de Persona")]
        public int PersonaID { get; set; }

        [Required(ErrorMessage = "Este campo es requerido")]
        [MaxLength(50, ErrorMessage = "La longitud máxima del campo es de 200 caracteres")]
        [Display(Name = "Numero de Telefono")]
        public string NroTelefono { get; set; }
    }
}

Controllers/PersonasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using proyectoABMC.Database;
using proyectoABMC.Models;

namespace proyectoABMC.Controllers
{
    public class PersonasController : Controller
    {
        private readonly ProyectoAbmcDbContext _context;

        public PersonasController(ProyectoAbmcDbContext context)
        {
            _context = context;
        }

        public IActionResult Index(string? nombre)
        {
            if (nombre != null)
            {
                return View(nameof(Index), _context.Personas.Where(P => P.Nombre.Equals(nombre)).ToList());
            }
            return View(_context.Personas.ToList());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("PersonaId,Nombre,FechaNacimiento,CreditoMaximo")] Persona persona)
        {
            if (ModelState.IsValid)
            {
                _context.Add(persona);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(persona);
        }

        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var persona = _context.Personas.Find(id);
            if (persona == null)
            {
                return NotFound();
            }
            return View(persona);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("PersonaId,Nombre,FechaNacimiento,CreditoMaximo")] Persona persona)
        {
            if (id != persona.PersonaId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(persona);
                    _context.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PersonaExists(persona.PersonaId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(persona);
        }


        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var persona = _context.Personas
                .FirstOrDefault(m => m.PersonaId == id);
            if (persona == null)
            {
                return NotFound();
            }

            return View(persona);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var persona = _context.Personas.Find(id);
            _context.Personas.Remove(persona);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        private bool PersonaExists(int id)
        {
            return _context.Personas.Any(e => e.PersonaId == id);
        }
    }
}

Controllers/TelefonosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using proyectoABMC.Database;
using proyectoABMC.Models;

namespace proyectoABMC.Controllers
{
    public class TelefonosController : Controller
    {
        private readonly ProyectoAbmcDbContext _context;

        public TelefonosController(ProyectoAbmcDbContext context)
        {
            _context = context;
        }

        public IActionResult Index(int id)
        {
            if (id != 0)
            {
                return View(nameof(Index),_context.Telefonos.Where(P => P.PersonaID.Equals(id)).ToList());
            }
            return View(_context.Telefonos.ToList());
        }

        public IActionResult Create(int id)
        {
            ViewData["PersonaId"] = new SelectList(_context.Personas.Where(P => P.PersonaId.Equals(id)), "PersonaId", "Nombre");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Telefono telefono)
        {
            if (ModelState.IsValid)
            {
                _context.Add(telefono);
                _context.SaveChanges();
                return Index(id:telefono.PersonaID);
            }
            ViewData["PersonaID"] = new SelectList(_context.Personas, "PersonaId", "Nombre", telefono.PersonaID);
            return View(telefono);
        }

        public IActionResult Edit(int? id)
        {
            ViewData["PersonaId"] = new SelectList(_context.Personas, "PersonaId", "Nombre");
            if (id == null)
            {
                return NotFound();
            }

            var telefono = _context.Telefonos.Find(id);
            if (telefono == null)
            {
                return NotFound();
            }
            return View(telefono);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, Telefono telefono)
        {
            if (id != telefono.TelefonoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(telefono);
                    _context.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TelefonoExists(telefono.TelefonoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["PersonaID"] = new SelectList(_context.Personas, "PersonaId", "Nombre", telefono.PersonaID);
            return View(telefono);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var telefono = _context.Telefonos
                .FirstOrDefault(m => m.TelefonoId == id);
            if (telefono == null)
            {
                return NotFound();
            }

            return View(telefono);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var telefono = _context.Telefonos.Find(id);
            _context.Telefonos.Remove(telefono);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        private bool TelefonoExists(int id)
        {
            return _context.Telefonos.Any(e => e.TelefonoId == id);
        }
    }
}

Views/Telefonos/Create.cshtml
@model proyectoABMC.Models.Telefono

@{
    ViewData["Title"] = "Create";
}
<h1>Añadir telefono.</h1>

@{
    var aID = ViewContext.RouteData.Values["id"];
}
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NroTelefono" class="control-label"></label>
                <input asp-for="NroTelefono" class="form-control" />
                <span asp-validation-for="NroTelefono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <select asp-for="PersonaID" class="form-control" asp-items="ViewBag.PersonaId" hidden></select>
                <span asp-validation-for="PersonaID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Confirmar" class="btn btn-success" />
                <a asp-action="Index" asp-route-id="@aID" class="btn btn-danger">Cancelar</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Telefonos/Delete.cshtml
@model proyectoABMC.Models.Telefono

@{
    ViewData["Title"] = "Delete";
}
<h3>Confirmacion de eliminacion del telefono @Model.NroTelefono</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PersonaID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PersonaID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NroTelefono)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NroTelefono)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="TelefonoId" />
        <input type="submit" value="Borrar" class="btn btn-danger" /> 
        <a asp-action="Index" asp-route-id="@Model.PersonaID"class="btn btn-success" >Cancelar</a>
    </form>
</div>

Views/Telefonos/Edit.cshtml
@model proyectoABMC.Models.Telefono

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Telefono</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="TelefonoId" />
            <div class="form-group">
                <label asp-for="PersonaID" class="control-label"></label>
                <select asp-for="PersonaID" class="form-control" asp-items="ViewBag.PersonaId"></select>
                <span asp-validation-for="PersonaID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NroTelefono" class="control-label"></label>
                <input asp-for="NroTelefono" class="form-control" />
                <span asp-validation-for="NroTelefono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
                <a asp-action="Index" asp-route-id="@Model.PersonaID" class="btn btn-danger">Cancelar</a>
            </div>
        </form>
    </div>
</div>

<div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Telefonos/Index.cshtml
@model IEnumerable<proyectoABMC.Models.Telefono>

@{
    ViewData["Title"] = "Index";
}

<h1 class="d-flex justify-content-center mb-3">Grilla de Telefonos</h1>
@{
    var aID = ViewContext.RouteData.Values["id"];
}
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PersonaID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NroTelefono)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.PersonaID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NroTelefono)
                </td>
                <td class="d-flex justify-content-end">
                    <a asp-action="Edit" asp-route-id="@item.TelefonoId" class="btn btn-outline-info">Editar</a>
                    <a asp-action="Delete" asp-route-id="@item.TelefonoId" class="btn btn-outline-danger">Borrar</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<hr />
<p class="d-flex justify-content-between">
    <a asp-action="Index" asp-controller="Personas" class="btn btn-warning">Volver</a>
    <a asp-action="Create" asp-route-id="@aID" class="btn btn-primary">Nuevo telefono</a>
</p>